on:
  push:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: docfx-action
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: documentation/docfx.json

      - uses: maxheld83/ghpages@master
        env:
          BUILD_DIR: documentation/_site
          GH_PAT: ${{ secrets.GH_PAT }}
