on:
  push:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: docfx-action
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: documentation/docfx.json
