on: workflow_dispatch
    
permissions:
  contents: write

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Copy README.md to index.md
        run: find . -name "README.md" -exec sh -c 'cp "{}" "$(dirname {})/index.md"' \;
        
      - name: List Tree
        run: ls -R
      
      - name: Generate Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: documentation/docfx.json

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/_site
